### ISSUE TITLE
recreate tests

### ISSUE THREAD

**Issue by arades79** [arades79/hyperdome#15]
Tests from onionshare source need to be updated where applicable for hyperdome

**Comment by stevenpitts** [comment]
Plans:
Stage 1: Write a test script that takes care of opening the server and using requests to mimic the client. Should be completely automated.
Stage 2: Rewrite some of the code to allow for future stages; everything is currently module-level, which makes it difficult to test. Some module-level code might need to become part of a class.
Stage 3: Stage 1, but open two client GUIs instead, and have the programmer perform some actions such as connecting and sending messages. A master thread will be detecting whether any errors happen during usage.
Stage 4: Automate the GUI actions. Depending on the outcomes of previous stages and how easy it is to do unit tests for PyQT UIs, this may not be worth it.
Will update this message as pushes are made.

**Comment by stevenpitts** [comment]
I am normally all for PRs having only one purpose, but given the status of the program, I am also going to fix some bugs as I go. Otherwise, it would be extremely difficult to write tests knowing that prior tests are going to fail.

**Comment by arades79** [comment]
integration test in #36 acceptable for milestone.
