### ISSUE TITLE
Should IPv6 be supported?

### ISSUE THREAD

**Issue by arades79** [arades79/hyperdome#20]
Tor IPv6 support is still relatively new, and according to their documentation "Note that as of 2018 there aren't many IPv6 users, or IPv6 guards, so Tor over IPv6 is less anonymous than Tor over IPv4"

https://2019.www.torproject.org/docs/faq.html.en#IPv6

Perhaps this should be an option. Should hyperdome adoption ever be wide enough, it may be a good source of IPv6 relays.

**Comment by stevenpitts** [comment]
I'd say we make it an option now, then maybe in the future we change the default from IPv6-disabled to IPv6-enabled, once IPv6 is more widely used.

**Comment by arades79** [comment]
A setting will be added to the client. A setting should also be added to the server in the form of a command line argument.

We'll follow the opt-in/opt-out/remove model, following the lead of other tor based projects to ensure enough clients are capable of ipv6 that it's not a de-anonymization risk.
