### ISSUE TITLE
Should older Python versions continue to be supported?

### ISSUE THREAD

**Issue by stevenpitts** [arades79/hyperdome#24]
Onionshare does a good job of keeping code working on older versions of Python, but that limits us to older features of the language, which will make for less elegant code. Can we enforce Python3.7, or should we continue support of older Python3 versions?

**Comment by arades79** [comment]
considering the final application ships as a static binary, I would think the project shouldn't be restricted to support multiple versions.

Version support will likely be pending on the quality of a feature. If a PR is submitted with a well made feature that breaks compatibility for older python versions, dropping support would be considered.
