### ISSUE TITLE
change default hidden service behavior

### ISSUE THREAD

**Issue by arades79** [arades79/hyperdome#39]
Onionshare defaults to creating an ephemeral unique hidden service every time one is spawned. While this functionality could be useful in some contexts, this should not be the default for Hyperdome systems. Users should expect consistent server URLs, and the ability to skip creating and destroying hidden services for every server launch will be a better experience.

Slug URLs are also unused, and the functionality of these slugs is not necessary for Hyperdome's use case. Thus the default behavior should not create or attach slug endpoints.

**Comment by stevenpitts** [comment]
Oops lol, I was writing this issue at the same time


The onion connection fails too often.
Usually it works fine when you run the code once (using hyperdome_connection.py as a test), but after running it a few times, the onion will fail to connect multiple times in a row.
Happens in `hyperdome_server.onion.connect` https://github.com/arades79/hyperdome/blob/95fb25d73ea39d84a4a37d03cc656088f078f3a8/hyperdome_server/onion.py#L188
At a lower level, it is happening at `stem.control.Controller.create_ephemeral_hidden_service`, where it is trying to get from an empty queue in blocking mode (waiting for something to be added).
The current quickfix is just having a 10 second timeout, and having a set number of retries. This usually, but not always, works eventually.
Given its occurrence patterns, it would seem to be a cleanup issue. Maybe we need to close the ports better? Or maybe tor just wasn't meant to connect in rapid succession like this?
Additional research required.
Goal: Eliminate repeated failure of onion connection.

**Comment by arades79** [comment]
Oops, the error is still occurring after the merged changes, other configuration will need to change to fix, and potential underlying issue is yet to be addressed.
